import Home from "./page";
import Header from "./components/header";
import Footer from "./components/footer";
import { Metadata } from "next";

export const metadata = {
  title: {
    absolute: "",
    default: "Nafiur",
    template: "%s | Nafiur",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
